const APP_VERSION='6.0.0', USER_NAME='Jahran', LEVELS=['A1','A2','B1','B2','C1','C2'];
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}; const pick=a=>a[Math.floor(Math.random()*a.length)];
const norm=s=>String(s??'').toLowerCase().replace(/\d+/g,'#').replace(/[^a-z0-9 ]+/g,' ').replace(/\s+/g,' ').trim();
const stateKey='fiezel-v6-state';
const defaultState={version:APP_VERSION,userName:USER_NAME,view:'home',level:1,placementDone:false,totalAnswered:0,totalCorrect:0,totalTimeMs:0,history:[],wrongAnswers:[],vocab:{},grammar:{},reading:{},daily:{date:'',count:0},streak:0,chat:[],flash:{}};
let state=loadState(),V=[],R=[],G=[],LT=[],questionHistory=new Set();
function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem(stateKey)),vocab:{},grammar:{},reading:{},history:[],wrongAnswers:[],chat:[],flash:{},...JSON.parse(localStorage.getItem(stateKey))}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(stateKey,JSON.stringify(state))}
function today(){return new Date().toISOString().slice(0,10)}
function mastery(bucket,key){return state[bucket][key]||{correct:0,total:0,mastery:0,streak:0,lastSeen:0,lastWrong:0,nextReview:0,responseTime:0}}
function updateMastery(bucket,key,ok,ms=0){const b=mastery(bucket,key);b.total++;b.correct+=ok?1:0;b.streak=ok?b.streak+1:0;b.mastery=Math.round(b.correct/b.total*100);b.lastSeen=Date.now();if(!ok)b.lastWrong=Date.now();b.responseTime=Math.round(((b.responseTime||0)*(b.total-1)+ms)/b.total);const days=ok?[1,2,4,7,14,30][Math.min(5,Math.max(0,b.streak-1))]:0.25;b.nextReview=Date.now()+days*86400000;state[bucket][key]=b;save()}
function record(q,ok,ms){state.totalAnswered++;state.totalCorrect+=ok?1:0;state.totalTimeMs+=ms;state.history.push({id:q.id,type:q.type,skill:q.skill||'general',ok,ms,at:Date.now()});if(!ok)state.wrongAnswers.push({id:q.id,correct:q.options?.[q.answerIndex],skill:q.skill,at:Date.now()});state.history=state.history.slice(-2000);state.wrongAnswers=state.wrongAnswers.slice(-500);save()}
async function load(){const get=async f=>{const r=await fetch(f+'?v='+APP_VERSION,{cache:'no-store'});if(!r.ok)throw Error(`${f}: HTTP ${r.status}`);return r.json()};[V,R,G,LT]=await Promise.all(['vocabulary-master.json','reading-bank.json','grammar-bank.json','level-test-bank.json'].map(get));}
function go(v){state.view=v;save();render()}
function shell(title,sub,body){$('app').innerHTML=`<section class="fade"><div class="eyebrow">FIEZEL · V6</div><h1>${esc(title)}</h1><p class="muted">${esc(sub)}</p>${body}</section>`}
function card(x,c=''){return `<div class="card ${c}">${x}</div>`}
function stat(a,b){return `<div class="stat"><small>${esc(a)}</small><strong>${esc(b)}</strong></div>`}
function render(){document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===state.view));({home,vocab,practice,adaptive,chat,progress}[state.view]||home)()}
function home(){const acc=state.totalAnswered?Math.round(state.totalCorrect/state.totalAnswered*100):0;const due=countDue();shell(`Hi ${USER_NAME} 👋`,'Verified local-first learning core. No AI API.',card(`<div class="stats">${stat('Level',state.placementDone?LEVELS[state.level-1]:'A1')}${stat('Accuracy',acc+'%')}${stat('Review',due)}${stat('Answered',state.totalAnswered)}</div>`,'hero')+card(`<h3>Continue learning</h3><div class="grid"><button class="primary" onclick="openFlashcard()">🗂 Flashcards</button><button onclick="startVocabQuiz()">📚 Vocabulary Quiz</button><button onclick="go('adaptive')">✦ Adaptive Practice</button><button onclick="startPlacement()">🎯 Level Test · 150</button></div>`)+card(`<h3>Learning library</h3><div class="library">${V.length} vocabulary · ${R.length} reading passages · ${G.length} grammar questions · ${LT.length} placement questions</div>`))}
function vocab(){shell('Vocabulary Hub','One Master Vocabulary source. Tap a card to hear pronunciation and review meaning in context.',card(`<div class="toolbar"><button class="primary" onclick="openFlashcard()">🗂 Flashcards</button><button onclick="startVocabQuiz()">Quiz</button></div>`)+card(`<div class="grid">${LEVELS.map(l=>`<button onclick="startVocabLevel('${l}')"><b>${l}</b><br><span class="muted">${V.filter(v=>v.level===l).length} words</span></button>`).join('')}</div>`))}
function vocabScore(v){const s=mastery('vocab',v.id);let score=(100-(s.mastery||0))*0.45;if(s.nextReview&&s.nextReview<=Date.now())score+=35;if(s.lastWrong&&Date.now()-s.lastWrong<7*86400000)score+=25;if(!s.total)score+=18;score+=(Math.random()*4);return score}
function adaptivePool(){const due=V.filter(v=>{const s=mastery('vocab',v.id);return s.nextReview&&s.nextReview<=Date.now()});return shuffle([...due].sort((a,b)=>vocabScore(b)-vocabScore(a)).concat([...V].sort((a,b)=>vocabScore(b)-vocabScore(a)))).filter((v,i,a)=>a.findIndex(x=>x.id===v.id)===i).slice(0,60)}
function makeVocabQuestion(v){const correct=String(v.meaning||'').trim();if(!correct)return null;const pool=V.filter(x=>x.id!==v.id&&x.meaning&&norm(x.meaning)!==norm(correct));const others=[];for(const x of shuffle(pool)){if(!others.some(o=>norm(o)===norm(x.meaning)))others.push(x.meaning);if(others.length===3)break}if(others.length<3)return null;const options=shuffle([correct,...others]);const answerIndex=options.indexOf(correct);if(answerIndex<0)return null;return{id:`vq-${v.id}-${norm(correct).slice(0,12)}`,type:'vocab',skill:'vocabulary_meaning',target:v.id,difficulty:v.difficulty,question:`What is the closest Indonesian meaning of “${v.word}”?`,options,answerIndex,explain:{why:`“${v.word}” means “${correct}” in the Master Vocabulary.`,rule:`Vocabulary · ${v.level}`,avoid:'Use the example and context to reinforce the meaning.'}}}
function startVocabQuiz(){const qs=adaptivePool().map(makeVocabQuestion).filter(Boolean);if(qs.length<5){toast('Vocabulary question pool gagal validasi. Tidak ada soal yang dirender.');return}quizLoop({type:'vocab',count:10,pool:qs})}
function startVocabLevel(l){const qs=V.filter(v=>v.level===l).map(makeVocabQuestion).filter(Boolean);if(qs.length<5){toast('Level vocabulary belum memiliki cukup soal valid.');return}quizLoop({type:'vocab',count:10,pool:qs})}
function openFlashcard(){let pool=adaptivePool();if(!pool.length){toast('Tidak ada flashcard valid.');return}let i=0;function draw(){const v=pool[i%pool.length],s=mastery('vocab',v.id);shell('Flashcards',`${i+1}/${Math.min(pool.length,20)} · ${v.level} · ${v.partOfSpeech||'word'}`,`<div class="flash" id="flash" onclick="flipFlash()"><div class="flash-inner"><div class="face front"><div class="eyebrow">WORD</div><div class="word">${esc(v.word)}</div><div class="phonetic">${esc(v.phonetic||'Pronunciation not verified')}</div><div class="audio-row"><button class="audio" onclick="event.stopPropagation();speakWord('${encodeURIComponent(v.word)}')">🔊 Listen word</button></div><p class="muted">Tap the card to reveal the meaning.</p></div><div class="face back"><div class="eyebrow">MEANING</div><h2>${esc(v.meaning)}</h2><p class="muted">${esc(v.usageNotes||'Use the word in context and listen to its pronunciation.')}</p><hr><h3>Example</h3><p>${esc(v.example||'Example not verified yet.')}</p><p class="muted">${esc(v.exampleTranslation||'Example translation is not verified yet.')}</p><div class="audio-row"><button class="audio" onclick="event.stopPropagation();speakWord('${encodeURIComponent(v.word)}')">🔊 Word</button><button class="audio" onclick="event.stopPropagation();speakExample('${encodeURIComponent(v.example||'')}')">🔊 Example</button></div><p class="muted">Mastery: ${s.mastery||0}%</p></div></div></div>${card(`<div class="row"><b>How well did you remember it?</b></div><div class="grid"><button onclick="rateFlash('${v.id}','again')">Again</button><button onclick="rateFlash('${v.id}','hard')">Hard</button><button class="primary" onclick="rateFlash('${v.id}','good')">Good</button><button onclick="rateFlash('${v.id}','easy')">Easy</button></div>`)}${card(`<button onclick="startVocabQuiz()">Quiz this vocabulary →</button>`)}`)}window._flashDraw=draw;draw()}
function flipFlash(){$('flash')?.classList.toggle('flipped')}
function rateFlash(id,r){const b=state.vocab[id]||{correct:0,total:0,mastery:0,streak:0};b.total++;const delta={again:-12,hard:-3,good:8,easy:14}[r];b.mastery=Math.max(0,Math.min(100,(b.mastery||0)+delta));b.lastSeen=Date.now();b.nextReview=Date.now()+({again:0.03,hard:1,good:3,easy:7}[r])*86400000;state.vocab[id]=b;save();sound(r==='again'?'wrong':'correct');toast(r==='easy'?`Excellent, ${USER_NAME}!`:r==='again'?`Semangat, ${USER_NAME}!`:`Good work, ${USER_NAME}!`);window._flashDraw?.()}
function speak(text,rate=0.88){if(!('speechSynthesis' in window)){toast('Text-to-speech tidak tersedia di browser ini.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=rate;u.pitch=1;setTimeout(()=>speechSynthesis.speak(u),40)}
function speakWord(encoded){speak(decodeURIComponent(encoded),0.78)}function speakExample(encoded){speak(decodeURIComponent(encoded),0.86)}
function sound(kind){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=kind==='correct'?660:220;g.gain.value=.035;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.12)}catch{}}
function grammar(){shell('Grammar Lab','Grammar questions are linked to Master Vocabulary where the source supports it.',card(`<div class="grid"><button class="primary" onclick="adaptiveGrammar()">⚡ Adaptive Grammar</button>${LEVELS.map(l=>`<button onclick="grammarLevel('${l}')">${l} · ${G.filter(q=>q.level===l).length}</button>`).join('')}</div>`))}
function adaptiveGrammar(){const pool=G.map(q=>({q,s:mastery('grammar',q.skill)})).sort((a,b)=>(100-(a.s.mastery||0))-(100-(b.s.mastery||0))).reverse().map(x=>x.q);quizLoop({type:'grammar',count:10,pool})}
function grammarLevel(l){quizLoop({type:'grammar',count:10,pool:G.filter(q=>q.level===l)})}
function reading(){shell('Reading Lab','Passage-based questions. Every answer must exist in the current passage options.',card(`<div class="grid">${LEVELS.map(l=>`<button onclick="readingLevel('${l}')">${l} · ${R.filter(r=>r.level===l).length} passages</button>`).join('')}</div>`))}
function readingLevel(l){const rs=R.filter(r=>r.level===l);if(!rs.length)return;const r=pick(rs);quizLoop({type:'reading',count:5,pool:r.qs,context:r})}
function practice(){shell('Practice Center','Choose a focused mode or let FIEZEL adapt the session to your weaknesses.',card(`<div class="grid"><button class="primary" onclick="go('adaptive')">✦ Adaptive Practice</button><button onclick="adaptiveGrammar()">🧩 Grammar</button><button onclick="readingLevel('A1')">📖 Reading</button><button onclick="startPlacement()">🎯 Level Test · 150</button></div>`)+card(`<h3>Question integrity</h3><p class="muted">FIEZEL refuses to render a question when the answer index is invalid, options are duplicated, or the correct option is missing.</p>`))}
function adaptive(){const vDue=V.filter(v=>{const s=mastery('vocab',v.id);return s.nextReview&&s.nextReview<=Date.now()}).length;const weakG=Object.entries(state.grammar).sort((a,b)=>(a[1].mastery||0)-(b[1].mastery||0))[0]?.[0]||'Not measured';const weakR=Object.entries(state.reading).sort((a,b)=>(a[1].mastery||0)-(b[1].mastery||0))[0]?.[0]||'Not measured';shell('Adaptive Practice',`FIEZEL chooses the next skill from your history, mistakes, mastery, response time, and review schedule.`,card(`<div class="stats">${stat('Vocab review',vDue)}${stat('Weak grammar',weakG.replaceAll('_',' '))}${stat('Weak reading',weakR.replaceAll('_',' '))}${stat('Accuracy',state.totalAnswered?Math.round(state.totalCorrect/state.totalAnswered*100)+'%':'—')}</div>`)+card(`<h3>Personalized session</h3><p class="muted">Priority: review due → recent mistakes → low mastery → unseen material. The same question ID is not reused in the current session history.</p><button class="primary" onclick="startAdaptive()">Start Adaptive Practice →</button>`))}
function startAdaptive(){const candidates=[];const due=V.filter(v=>{const s=mastery('vocab',v.id);return s.nextReview&&s.nextReview<=Date.now()}).sort((a,b)=>vocabScore(b)-vocabScore(a)).slice(0,4);due.forEach(v=>{const q=makeVocabQuestion(v);if(q)candidates.push(q)});const weakG=G.slice().sort((a,b)=>(mastery('grammar',a.skill).mastery||0)-(mastery('grammar',b.skill).mastery||0)).slice(0,4);candidates.push(...weakG);const weakR=R.flatMap(r=>r.qs.map(q=>({...q,contextId:r.id}))).sort((a,b)=>(mastery('reading',a.contextId||a.id).mastery||0)-(mastery('reading',b.contextId||b.id).mastery||0)).slice(0,4);candidates.push(...weakR);const valid=candidates.filter(q=>validateQuestion(q));if(valid.length<3){toast('Adaptive pool belum cukup valid.');return}quizLoop({type:'adaptive',count:Math.min(10,valid.length),pool:valid})}
function countDue(){return V.filter(v=>{const s=mastery('vocab',v.id);return s.nextReview&&s.nextReview<=Date.now()}).length}
function startPlacement(){if(LT.length!==150){toast('Level Test invalid: bank harus tepat 150 soal.');return}quizLoop({type:'placement',count:150,pool:shuffle(LT),placement:true})}
function validateQuestion(q){return !!q&&Array.isArray(q.options)&&q.options.length>=2&&q.answerIndex>=0&&q.answerIndex<q.options.length&&new Set(q.options.map(norm)).size===q.options.length&&String(q.options[q.answerIndex]||'').trim().length>0&&String(q.question||'').trim().length>5}
function quizLoop(cfg){let questions=shuffle(cfg.pool).filter(validateQuestion).filter(q=>{const s=q.id;if(questionHistory.has(s))return false;questionHistory.add(s);return true}).slice(0,cfg.count),i=0,score=0,start=Date.now();if(cfg.placement&&questions.length!==150){toast(`Level Test hanya menemukan ${questions.length} soal valid. Tidak dimulai.`);return}if(!questions.length){toast('Tidak ada soal valid.');return}function draw(){if(i>=questions.length){finishQuiz(cfg,score,questions.length);return}const q=questions[i],context=cfg.context;let body='';if(context)body+=card(`<div class="passage"><b>${esc(context.title)}</b><p>${esc(context.text)}</p></div>`);body+=card(`<div class="eyebrow">${esc(q.skill||q.type)} · ${esc(q.difficulty||'adaptive')}</div><h2 class="question">${esc(q.question)}</h2><div id="options" class="options"></div><div id="feedback" class="feedback hidden"></div>`);$('app').innerHTML=`<section class="fade"><div class="topline"><button onclick="go('home')">← Exit</button><span>${i+1}/${questions.length}</span></div>${body}</section>`;const buttons=q.options.map((o,j)=>{const b=document.createElement('button');b.className='option';b.textContent=o;b.onclick=()=>answer(j);return b});$('options').append(...buttons);function answer(j){buttons.forEach(b=>b.disabled=true);const ok=j===q.answerIndex,ms=Date.now()-start;if(ok){score++;buttons[j].classList.add('correct');sound('correct')}else{buttons[j].classList.add('wrong');buttons[q.answerIndex]?.classList.add('correct');sound('wrong')}record(q,ok,ms);if(q.type==='vocab'||q.target)updateMastery('vocab',q.target,ok,ms);if(q.type==='grammar')updateMastery('grammar',q.skill,ok,ms);if(q.type==='reading'||cfg.type==='adaptive'&&q.contextId)updateMastery('reading',q.contextId||q.id,ok,ms);const correct=q.options[q.answerIndex];const f=$('feedback');f.classList.remove('hidden');f.innerHTML=`<b>${ok?'✓ Kamu hebat, '+esc(USER_NAME)+'!':'Semangat, '+esc(USER_NAME)+'!'}</b><p><strong>Jawabanmu:</strong> ${esc(q.options[j])}</p><p><strong>Jawaban benar:</strong> ${esc(correct)}</p><p><strong>Why?</strong> ${esc(q.explain?.why||'Periksa konteks dan bukti yang mendukung jawaban.')}</p><p><strong>Rule:</strong> ${esc(q.explain?.rule||q.skill||'Review the relevant skill.')}</p><p><strong>How to avoid:</strong> ${esc(q.explain?.avoid||'Baca seluruh kalimat atau passage sebelum memilih.')}</p>${ok?'':'<p><strong>Quick-check:</strong> Pilih jawaban yang sama pada pertanyaan berikutnya yang berbeda.</p>'}<button class="primary" id="nextBtn">${ok?'Next →':'Next / Remedial →'}</button>`;document.getElementById('nextBtn').onclick=()=>{i++;start=Date.now();draw()}}}draw()}
function finishQuiz(cfg,score,total){if(cfg.placement){const pct=Math.round(score/total*100);state.level=pct<35?1:pct<50?2:pct<65?3:pct<78?4:pct<90?5:6;state.placementDone=true;save()}toast(score/total>=.85?`Kamu luar biasa, ${USER_NAME}!`:`Semangat, ${USER_NAME}!`);$('app').innerHTML=`<section class="fade center">${card(`<div class="score">${Math.round(score/total*100)}%</div><h2>${cfg.placement?'Level Test selesai':'Latihan selesai'}</h2><p>${score} dari ${total} benar.</p><button class="primary" onclick="go('home')">Kembali ke Home</button>`,'hero')}</section>`}
function chat(){shell('FIEZEL','Local interactive English tutor. Context is kept on-device.',card(`<div id="chatlog" class="chatlog">${state.chat.map(m=>`<div class="bubble ${m.role==='user'?'user':'bot'}">${esc(m.text)}</div>`).join('')}</div>`)+`<div class="chatbox"><input id="chatInput" placeholder="Ask FIEZEL about a word, grammar, or quiz…"><button class="primary" onclick="sendChat()">Send</button></div>`);if(!state.chat.length)addBot(`Hi ${USER_NAME}! 👋\nAsk me about a vocabulary word, its meaning, pronunciation, example, grammar, or say “quiz me”.`)}
function addBot(text){state.chat.push({role:'bot',text});state.chat=state.chat.slice(-60);save();if(state.view==='chat')render()}
function sendChat(){const el=$('chatInput');const text=(el?.value||'').trim();if(!text)return;state.chat.push({role:'user',text});el.value='';save();const reply=chatReply(text);addBot(reply)}
function chatReply(t){const s=t.toLowerCase();const match=V.find(v=>new RegExp('\\b'+v.word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b','i').test(t));if(s.includes('quiz'))return`Sure, ${USER_NAME}. Let's practice a question from your current adaptive pool.\n\nTap “Adaptive” to start a validated session.`;if(match){if(s.includes('pronoun')||s.includes('say')||s.includes('how do i pronounce')){setTimeout(()=>speak(match.word,.78),80);return`The word is “${match.word}”.\nPronunciation: ${match.phonetic||'not verified'}\n\nI’ll play the English pronunciation now.`}if(s.includes('example'))return`“${match.word}” means ${match.meaning}.\n\nExample:\n${match.example||'Example not verified yet.'}\n\n${match.exampleTranslation||'The example translation is not verified yet.'}`;return`“${match.word}” means ${match.meaning}.\n\nPronunciation: ${match.phonetic||'not verified'}\nPart of speech: ${match.partOfSpeech||'not verified'}\n\n${match.usageNotes||'Use the word in context and listen to the pronunciation.'}`}if(s.includes('hello')||s.includes('hi'))return`Hi ${USER_NAME}! 👋 What would you like to practice?`;if(s.includes('present perfect'))return`Present perfect connects a past action to the present. A common form is: have/has + past participle. Example: “She has finished her work.”`;if(s.includes('past simple'))return`Past simple describes a completed past event. Example: “She visited the library yesterday.”`;return`I can help with vocabulary, pronunciation, examples, grammar, or adaptive practice. Try: “What does advance mean?”, “Give me an example of develop”, or “How do I pronounce construct?”`}
function progress(){const acc=state.totalAnswered?Math.round(state.totalCorrect/state.totalAnswered*100):0;const weak=Object.entries(state.grammar).sort((a,b)=>(a[1].mastery||0)-(b[1].mastery||0)).slice(0,6);shell('Progress','Everything stays on-device.',card(`<div class="stats">${stat('Answered',state.totalAnswered)}${stat('Accuracy',acc+'%')}${stat('Due',countDue())}${stat('Level',LEVELS[state.level-1])}</div>`)+card(`<h3>Weak grammar skills</h3>${weak.length?weak.map(([k,x])=>`<div class="meter"><div class="row"><span>${esc(k.replaceAll('_',' '))}</span><span>${x.mastery||0}%</span></div><div class="bar"><i style="width:${x.mastery||0}%"></i></div></div>`).join(''):'<p class="muted">Belum ada data. Mulai Adaptive Practice.</p>'}`)+card(`<button class="danger" onclick="resetProgress()">Reset Progress</button>`))}
function toast(t){const x=$('toast');x.textContent=t;x.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>x.classList.remove('show'),3000)}
function showGreeting(){const g=$('greeting');if(localStorage.getItem('fiezel-v6-greeted')==='today-'+today()){g.classList.add('hidden');return}g.classList.remove('hidden');$('greetingText').textContent=`Hi, ${USER_NAME}!`;$('greetingSub').textContent='Ready to make progress today?';setTimeout(()=>{g.classList.add('hidden');localStorage.setItem('fiezel-v6-greeted','today-'+today())},3200)}
$('greetSkip').onclick=()=>{$('greeting').classList.add('hidden');localStorage.setItem('fiezel-v6-greeted','today-'+today())};
function resetProgress(){if(confirm('Reset seluruh progress FIEZEL V6?')){localStorage.removeItem(stateKey);location.reload()}}
Object.assign(window,{go,startVocabQuiz,startVocabLevel,openFlashcard,flipFlash,speakWord,speakExample,rateFlash,adaptive,startAdaptive,sendChat,startPlacement,grammar,reading,progress,resetProgress});
// Navigation aliases for keyboard/accessibility and backwards compatibility without legacy engines.
window.addEventListener('keydown',e=>{if(e.key==='Escape')go('home')});
load().then(()=>{render();showGreeting()}).catch(e=>{$('app').innerHTML=`<section class="fade">${card(`<h2>FIEZEL could not load its local content.</h2><p>${esc(e.message)}</p><button onclick="location.reload()">Retry</button>`,'hero')}</section>`});

if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=6.0.0',{updateViaCache:'none'}).catch(()=>{}))}
